SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 5000 AND 12000;

SELECT LAST_NAME, JOB_ID, to_char(HIRE_DATE, 'DD-MON-YY') as "HIRE_DATE"
FROM EMPLOYEES
WHERE LAST_NAME IN('Matos', 'Taylor')
order by hire_date;

SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES 
WHERE department_ıd IN (20,50)
ORDER BY LAST_NAME;

SELECT LAST_NAME as  "Employee", SALARY as "Monthly Salary"
FROM EMPLOYEES 
WHERE SALARY BETWEEN 5000 AND 12000 AND department_id IN (20,50)
order by 1;

SELECT LAST_NAME, to_char(HIRE_DATE, 'DD-MON-YYYY') as "HIRE_DATE"
FROM EMPLOYEES
WHERE to_char(HIRE_DATE, 'DD-MON-YYYY') LIKE '%%-%%-1994';

SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
order by 2 desc;

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > &enter;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE MANAGER_ID = &enter
order by &order;

SELECT LAST_NAME 
FROM EMPLOYEES
WHERE LAST_NAME LIKE '__a%' ;

SELECT LAST_NAME 
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%a%' AND  LAST_NAME LIKE '%e%' ;

SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE JOB_ID IN ('SA_REP','ST_CLERK') AND SALARY NOT IN (2500, 3500, 7000);

SELECT LAST_NAME AS "Employee", SALARY AS " Monthly Salary", COMMISSION_PCT AS "Commission"
FROM EMPLOYEES
WHERE COMMISSION_PCT = 0.2;

