INSERT INTO EMPLOYEES_ 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, (SALARY + SALARY*15.5/100) AS "New Salary", ((SALARY + SALARY*15.5/100) - SALARY) AS "Increase"
FROM EMPLOYEES_;

SELECT initcap(LAST_NAME) as "Last Name", length(last_name) as "Length"
FROM EMPLOYEES_
WHERE LAST_NAME LIKE 'A%' OR LAST_NAME LIKE 'J%' OR LAST_NAME LIKE 'M%'
order by 1 asc;

SELECT LAST_NAME AS "Name", length(last_name) AS "Length"
FROM EMPLOYEES_
WHERE LAST_NAME LIKE ('&Letter%')
ORDER BY 1 ASC;

SELECT LAST_NAME AS "Name", length(last_name) AS "Length"
FROM EMPLOYEES_
WHERE LAST_NAME LIKE upper('&Letter%')
ORDER BY 1 ASC;

SELECT LAST_NAME, round((sysdate-hire_date)/30, 0) AS "MONTHS_WORKED"
FROM EMPLOYEES_
ORDER BY 1 ASC;