SELECT to_char(sysdate, 'DD/MON/YY') AS "Date"
FROM dual;

INSERT INTO EMPLOYEES_ 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, (SALARY + SALARY*15.5/100) AS "New Salary"
FROM EMPLOYEES_;