INSERT INTO EMPLOYEES_ 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID
FROM EMPLOYEES;

SELECT EMPLOYEE_ID AS "#Emp", LAST_NAME AS "Employee", JOB_ID AS "Job", to_char(hire_date, 'DD/MM/YY')
FROM EMPLOYEES_;

SELECT  LAST_NAME || ', ' || JOB_ID AS "Name and Job"
FROM EMPLOYEES_
order by 1 asc;

