SELECT STUID, TITLE, BORROWDATE, RETURNDATE
FROM borrowıng_ borrow, books_ book
WHERE STUID = &student_id;

SELECT ISBN, TITLE, STNAME, STSURNAME, BORROWDATE, RETURNDATE
FROM STUDENTS_ s, BOOKS_ b, BORROWING_ bo
WHERE bo.STUID = s.STID and BISBN = ISBN;

SELECT ANAME, ASURNAME
FROM AUTHORS_, BORROWING_
WHERE borrowıng_.returndate NOT LIKE 'NULL';

SELECT TITLE 
FROM BOOKS_
WHERE TITLE LIKE '%Programming%';

SELECT STNAME, STSURNAME
FROM STUDENTS_
WHERE STNAME LIKE 'A%';

SELECT STNAME, STSURNAME
FROM STUDENTS_ s, AUTHORS_ a, BOOKS_ b, BORROWING_ bo, BOOKAUT_ ba
WHERE a.AID = ba.AUID 
and ba.ISBN = b.ISBN
and bo.BISBN =b.ISBN
and bo.STUID = s.STID
and a.Country IN ('USA');

SELECT STNAME, TITLE, BORROWDATE, RETURNDATE, DUEDATE
FROM BORROWING_ bo, STUDENTS_ s, BOOKS_ b
WHERE bo.STUID = s.STID 
and bo.BISBN = b.ISBN
and DUEDATE - RETURNDATE < 0;

SELECT STNAME, STSURNAME, TITLE
FROM BORROWING_ bo, STUDENTS_ s, BOOKS_ b
WHERE bo.STUID = s.STID 
and bo.BISBN = b.ISBN
and RETURNDATE IS NULL;


SELECT ANAME, ASURNAME
FROM AUTHORS_
WHERE COUNTRY IN('GERMANY')
order by 1 asc;

SELECT STNAME, STSURNAME
FROM STUDENTS_ s, BORROWING_ bo
WHERE bo.STUID = s.STID
and BISBN IN ('4-580-20-5','6-201-50-9');

SELECT TITLE, ANAME, ASURNAME
FROM BOOKS_ b, authors_ a, BOOKAUT_ bo
WHERE b.ISBN = bo.ISBN and bo.AUID = a.AID;

--------------------- Q12 AND Q13


SELECT STUID, BISBN, BORROWDATE - RETURNDATE AS "DAYS_BORROWED"
FROM STUDENTS_ s, BORROWING_ bo
WHERE bo.STUID = s.STID
and returndate IS not null;

SELECT STNAME, STSSURNAME, TITLE, BORROWDATE
FROM STUDENTS_ s, BOOKS_ b, BORROWING_ bo
WHERE bo.STUID = s. STID 
and bo.BISBN = b.ISBN 
and borrowdate BETWEEN to_date('&start_date', 'DD/MON/YY') and to_date('&end_date', 'DD/MON/YY');