alter table EMP2_ 
MODIFY LAST_NAME varchar2(50);
desc emp2_;

CREATE TABLE EMPLOYEES2_ AS
SELECT EMPLOYEE_ID ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID DEPT_ID
FROM EMPLOYEES; 
desc EMPLOYEES2_;

drop table emp2_;

select * from recyclebin;

flashback table emp2_ to before drop;
desc emp2_;

alter table employees2_
drop column first_name;

desc employees2_;

alter table emp2_
ADD CONSTRAINT EMP2_PK PRIMARY KEY (id);

ALTER TABLE DEPT_
ADD CONSTRAINT DEPT2_PK PRIMARY KEY (ID);

ALTER TABLE EMP2_
ADD CONSTRAINT EMPK_FK FOREIGN KEY (ID) references DEPT_(ID);

ALTER TABLE EMP2_
ADD COMISSION number(2,2)
CONSTRAINT EMP2_CHECK_COM CHECK (COMISSION > 0);

DROP TABLE EMP2_ PURGE;
DROP TABLE DEPT_ PURGE;
------------------------------------------ PART 2
CREATE TABLE EMPLOYEES3 AS
SELECT EMPLOYEE_ID ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID DEPT_ID
FROM EMPLOYEES;

alter table EMPLOYEES3 READ ONLY;

INSERT INTO EMPLOYEES3 (FIRST_NAME, LAST_NAME, SALARY, DEPT_ID)
VALUES ('Grant', 'Marcie', 5678, 10);

alter table EMPLOYEES3 READ WRITE;

DROP TABLE EMPLOYEES3;

